game-by-virtuals/game-node

plugins/onChainActionsPlugin/.gitignore, plugins/onChainActionsPlugin/.npmignore, plugins/onChainActionsPlugin/README.md, plugins/onChainActionsPlugin/package-lock.json, plugins/onChainActionsPlugin/package.json, plugins/onChainActionsPlugin/src/.env.example, plugins/onChainActionsPlugin/src/example.ts, plugins/onChainActionsPlugin/src/index.ts, plugins/onChainActionsPlugin/src/onChainActionsPlugin.ts, plugins/onChainActionsPlugin/tsconfig.json
Integrated GOAT to GAME to allow any GAME agent to execute  more than +200 actions on chain for EVM, Solana, Sui, and many other networks.
Checkout the README to see it working :)
Example of an agent checking its USDC balance:
=> feat: Add onchain plugin

plugins/discordPlugin/.gitignore, plugins/discordPlugin/.npmignore, plugins/discordPlugin/README.md, plugins/discordPlugin/__test__/DiscordPlugin.test.ts, plugins/discordPlugin/jest.config.js, plugins/discordPlugin/package.json, plugins/discordPlugin/src/discordPlugin.ts, plugins/discordPlugin/src/example.ts, plugins/discordPlugin/src/index.ts, plugins/discordPlugin/tsconfig.json, plugins/telegramPlugin/.gitignore, plugins/telegramPlugin/.npmignore, plugins/telegramPlugin/README.md, plugins/telegramPlugin/__test__/TelegramPlugin.test.ts, plugins/telegramPlugin/jest.config.js, plugins/telegramPlugin/package-lock.json, plugins/telegramPlugin/package.json, plugins/telegramPlugin/src/example.ts, plugins/telegramPlugin/src/index.ts, plugins/telegramPlugin/src/telegramPlugin.ts, plugins/telegramPlugin/tsconfig.json
- added telegram client
- added telegram plugin
- added telegram example
- added telegram test cases
- added discord client
- added discord plugin
- added discord example
=> added telegram & discord client

plugins/discordPlugin/README.md, plugins/telegramPlugin/README.md
- fix telegram description and readme
- fix discord description and readme
=> Update README and description

src/agent.ts
This PR introduces the ability to save and load a `GameAgent` session, enhancing usability by allowing agents to persist their state between runs. This functionality is crucial for maintaining progress and managing long-running sessions effectively.
1. **Added `save()` Method**:
- Captures the agent's current state (`agentId`, `mapId`, `gameActionResult`) and returns it as a serializable object.
2. **Added `load()` Static Method**:
- Recreates a `GameAgent` instance using a previously saved state, including the ability to initialize with provided workers.
3. **Refactored Worker Initialization**:
- Introduced `initWorkers()` to set up workers after loading the saved state, ensuring proper agent-worker connections.
- **Session Persistence**: Save agent progress and resume seamlessly.
- …
=> Add save method and static load method to GameAgent class

plugins/discordPlugin/README.md, plugins/discordPlugin/src/example.ts, plugins/telegramPlugin/README.md
- add description for telegram
- add description for discord
=> Add more description for telegram and discord

plugins/s3Plugin/.env.example, plugins/s3Plugin/.gitignore, plugins/s3Plugin/.npmignore, plugins/s3Plugin/README.md, plugins/s3Plugin/package-lock.json, plugins/s3Plugin/package.json, plugins/s3Plugin/src/example.ts, plugins/s3Plugin/src/index.ts, plugins/s3Plugin/src/s3Plugin.ts, plugins/s3Plugin/tsconfig.json
Adds an S3 plugin with upload/download functionality. 
See the README and `example.ts` for more info. The basic pattern is to configure required params, like access keys and a predefined bucket name, and then you can prompt for writing a local file to the bucket, or downloading it locally:
```ts
const s3Plugin = new S3Plugin({
credentials: {
accessKeyId: "AKEXAMPLES3S",
secretAccessKey: "SKEXAMPLES3S,
},
region: "us-east-1",
bucket: "virtuals-game-bucket",
endpoint: "http://localhost:8014",
sslEnabled: false,
forcePathStyle: true,
});
// initialize and start agent...
const task1 = "Upload a file to the S3 bucket at the path `./package.json`";
const task2 =
"Upload a file to the S3 bucket at the path `./README.md` with key `hello/world` and use a signed URL with a TTL of 900 seconds"; …
```
=> feat: s3 plugin

plugins/rss3Plugin/src/example.ts
**Fixed spelling mistakes:**
- `"Retrive"` → `"Retrieve"`
- `"begining"` → `"beginning"`
=> Fix spelling errors in `example.ts`

plugins/echochambersPlugin/LICENSE, plugins/echochambersPlugin/README.md, plugins/echochambersPlugin/package-lock.json, plugins/echochambersPlugin/package.json, plugins/echochambersPlugin/src/echochambersPlugin.ts, plugins/echochambersPlugin/src/example.ts, plugins/echochambersPlugin/src/example_mock.ts, plugins/echochambersPlugin/src/index.ts, plugins/echochambersPlugin/src/types.ts, plugins/echochambersPlugin/tsconfig.json
This PR adds a new plugin that enables GAME Protocol agents to interact with Echochambers, providing functionality for message sending, history retrieval, and metrics analysis. The plugin follows the established patterns of other GAME Protocol plugins.
1. Message Sending
- `sendMessageFunction`: Send messages to Echochambers rooms with reasoning context
2. History Retrieval
- `getRoomHistoryFunction`: Get message history from specific rooms with customizable limits
3. Metrics Analysis
- `getRoomMetricsFunction`: Get metrics for specific rooms
- `getAgentMetricsFunction`: Get metrics for all agents in a room
- `getMetricsHistoryFunction`: Get historical metrics data for rooms
- New [EchochambersPlugin]() class for managing Echochambers interactions
- REST API integration
- Type-safe …
=> EchoChambers Integration

plugins/imageGenPlugin/README.md, plugins/imageGenPlugin/package.json, plugins/imageGenPlugin/src/example.ts, plugins/imageGenPlugin/src/imageGenPlugin.ts, plugins/imageGenPlugin/src/index.ts
Image generator using TogetherAI inference for BFL - Flux Scnhell
- Adds plugin for BFL - Flux Scnhell
- Fixes #27
=> imagegen plugin

examples/twitter.ts, src/agent.ts, src/api.ts, src/apiV2.ts, src/index.ts, src/interface/GameClient.ts
Added support for llm model selection
default model will be `Llama-3.3-70B-Instruct `
=> Added support for multi model

plugins/elfaAiPlugin/.gitignore, plugins/elfaAiPlugin/.npmignore, plugins/elfaAiPlugin/README.md, plugins/elfaAiPlugin/__test__/ElfaAiPlugin.test.ts, plugins/elfaAiPlugin/jest.config.js, plugins/elfaAiPlugin/package-lock.json, plugins/elfaAiPlugin/package.json, plugins/elfaAiPlugin/src/elfaAiPlugin.ts, plugins/elfaAiPlugin/src/example.ts, plugins/elfaAiPlugin/src/index.ts, plugins/elfaAiPlugin/tsconfig.json
This PR introduces the Elfa AI Plugin for Virtuals Game. The plugin integrates the Elfa AI API—providing real‑time crypto insights. It supports multiple endpoints including ping, key status, mentions, top mentions, search mentions, trending tokens, and smart account stats. Additionally, an example usage file (example.ts) and updated README have been added to guide developers through installation and integration.
Potentially solving 2 issues
https://github.com/game-by-virtuals/game-node/issues/37 https://github.com/game-by-virtuals/game-node/issues/32
Please review and merge.
=> Elfa AI Plugin

plugins/coingeckoMaopPlugin/README.md, plugins/coingeckoMaopPlugin/package.json, plugins/coingeckoMaopPlugin/src/coingeckoMaopPlugin.ts, plugins/coingeckoMaopPlugin/src/example.coinDataByID.ts, plugins/coingeckoMaopPlugin/src/example.coinPricesByAddress.ts, plugins/coingeckoMaopPlugin/src/example.coinPricesByIDs.ts, plugins/coingeckoMaopPlugin/src/example.coinsCategoriesList.ts, plugins/coingeckoMaopPlugin/src/example.coinsListWithMarketData.ts, plugins/coingeckoMaopPlugin/src/example.newPoolsByNetwork.ts, plugins/coingeckoMaopPlugin/src/example.specificPoolData.ts, plugins/coingeckoMaopPlugin/src/example.tokenInfoByAddress.ts, plugins/coingeckoMaopPlugin/src/example.tokenPriceByAddresses.ts, plugins/coingeckoMaopPlugin/src/example.topGainersLosersConfig.ts, plugins/coingeckoMaopPlugin/src/example.trendingPoolsByNetwork.ts, plugins/coingeckoMaopPlugin/src/example.trendingPoolsList.ts, plugins/coingeckoMaopPlugin/src/example.trendingSearchList.ts, plugins/coingeckoMaopPlugin/src/example.ts, plugins/coingeckoMaopPlugin/src/index.ts, plugins/coingeckoMaopPlugin/src/utils.ts
The Coingecko maop plugin made by Questflow, powered by Coingecko, seamlessly empowers G.A.M.E agents with cryptocurrency data fetching capabilities using the Coingecko API, enabling the retrieval of current market data without introducing any additional complexity.
=> feat: add  coingecko maop plugin

plugins/d.a.t.aPlugin/.env.example, plugins/d.a.t.aPlugin/.gitignore, plugins/d.a.t.aPlugin/.npmignore, plugins/d.a.t.aPlugin/README.md, plugins/d.a.t.aPlugin/package-lock.json, plugins/d.a.t.aPlugin/package.json, plugins/d.a.t.aPlugin/src/d.a.t.aPlugin.ts, plugins/d.a.t.aPlugin/src/example.ts, plugins/d.a.t.aPlugin/src/index.ts, plugins/d.a.t.aPlugin/tsconfig.json
https://docs.carv.io/d.a.t.a.-ai-framework/introduction
---
This PR adds a new plugin -- D.A.T.A. It is a new data fetching plugin which helps AI Agent to better understand on-chain/off-chain info.
---
Features (non-breaking change which adds functionality). Adding a new plugin for fetching on-chain/off-chain info for Agent.
---
This changes will greatly improve the Agent's knowledge when it comes to AI Agent.
Q:
- Which smart contract on Ethereum was called the most in the last 24 hours, and what is its primary function?
A:
- Searching the results from d.a.t.a, please wait a moment. I will provide you with the most called smart contract on Ethereum in the last 24 hours and its primary function.
- Summary:
In the last 24 hours, the Ethereum smart contract with the address …
=> [feat] CARV d.a.t.a Plugin

package-lock.json, package.json, plugins/twitterPlugin/package-lock.json, plugins/twitterPlugin/package.json, plugins/twitterPlugin/src/gameTwitterClient.ts, plugins/twitterPlugin/src/interface.ts, plugins/twitterPlugin/src/twitterClient.ts
added support to get the following:
- mentions
- following
- followers
=> [Twitter] mention followers following

plugins/twitterPlugin/package-lock.json, plugins/twitterPlugin/package.json, plugins/twitterPlugin/src/gameTwitterClient.ts, plugins/twitterPlugin/src/interface.ts, plugins/twitterPlugin/src/twitterClient.ts
=> Upload media

plugins/adNetworkPlugin/.gitignore, plugins/adNetworkPlugin/.npmignore, plugins/adNetworkPlugin/package-lock.json, plugins/adNetworkPlugin/package.json, plugins/adNetworkPlugin/src/adNetworkPlugin.ts, plugins/adNetworkPlugin/src/example.ts, plugins/adNetworkPlugin/src/index.ts, plugins/adNetworkPlugin/tsconfig.json
This PR adds the Ad Network plugin integration for the GAME SDK, enabling agents to interact with Vader AI's Ad Network platform. The plugin allows agents to fetch assigned campaigns, promote them on social media platforms, and notify the platform about campaign status changes.
- Added `AdNetworkPlugin` class with campaign management functions
- Added example implementation in `example.ts` (Mocks twitter worker for testing purposes)
- Added proper error handling and logging
- Implemented proper type definitions following GAME SDK patterns
- GAME API key
- Ad Network API key (test key: `test-user-api-key`)
1. Set environment variables:
```bash
export VIRTUALS_API_KEY="your-game-api-key"
export MONITIZE_API_KEY="test-user-api-key"
```
2. Run the example:
```bash
ts-node src/example.ts
``` …
=> Vader AI Ad Network Plugin

plugins/stateofmikaPlugin/.gitignore, plugins/stateofmikaPlugin/README.md, plugins/stateofmikaPlugin/__tests__/integration.test.ts, plugins/stateofmikaPlugin/__tests__/stateMikaPlugin.test.ts, plugins/stateofmikaPlugin/jest.config.js, plugins/stateofmikaPlugin/package-lock.json, plugins/stateofmikaPlugin/package.json, plugins/stateofmikaPlugin/src/index.ts, plugins/stateofmikaPlugin/src/stateMikaPlugin.ts, plugins/stateofmikaPlugin/tsconfig.json
GMika
- Created new StateMikaPlugin for querying state.gmika.io ; a source for real time information, image recognition, token data query across dexscreener, live info scraper, basically giving agents the empirical senses they always needed
- Implemented robust error handling for 400/500/401 responses
- Added retry logic with exponential backoff
- Added detailed error messages and logging
- Created comprehensive test suite
- Unit tests for all error cases
- Integration tests with real API
- High test coverage (89.28% branch coverage)
- Added TypeScript interfaces for API responses
- Implemented proper FormData handling
- Added proper API key validation
- Updated README with detailed usage instructions
=> Deploying State of Mika into GAME NODEJS SDK 

CONTRIBUTION_GUIDE.md
Add a section for `General Contribution Guidelines`.
For consistency with `Plugin Contribution Guidelines`, add `General Contribution Guidelines` section for `CONTRIBUTION_GUIDE.md`.
Not needed.
=> [Docs] Update Contribution Guide

plugins/acpPlugin/src/acpClient.ts, plugins/acpPlugin/src/acpPlugin.ts, plugins/acpPlugin/src/acpToken.ts
1. changed contract address
2. removed evaluation memo
=> Minor Fixes on ACP plugin

plugins/acpPlugin/README.md, plugins/acpPlugin/example/README.md
Add more context for ACP plugin readme.
- Point external devs to staging agent registry link.
- Add pre-requisites regarding buyer x seller ACP test runs.
=> [Docs] Update ACP Plugin Documentation

src/index.ts
=> export chatAgent

src/chatAgent.ts
This PR fixes the argument handling in ChatAgent before passing to execute:
- Properly formats args to match expected { value: string } structure
- Ensures type safety by converting values to strings
The change ensures that all arguments are correctly formatted before being passed to the execute function, preventing type mismatches and undefined arguments.
=> fix(chatAgent): ensure proper argument format for function execution

plugins/farcasterPlugin/package-lock.json, plugins/farcasterPlugin/package.json, plugins/rss3Plugin/package-lock.json
- Change package name from @virtuals-protocol/game-twitter-plugin to @virtuals-protocol/game-farcaster-plugin
- Update package name from @virtuals-protocol/game-twitter-plugin to @virtuals-protocol/game-rss3-plugin
=> refactor: update package names for Farcaster and RSS3 plugins

src/chatAgent.ts, src/index.ts
Enables users to initiate chats directly using a chatId, bypassing the need to always create a new chat through the chatAgent. This provides a more efficient way to access existing chats.
=> feat: Export Chat class and expose chatId and client properties

plugins/acpPlugin/example/reactive/.env.example, plugins/acpPlugin/example/reactive/README.md, plugins/acpPlugin/example/reactive/buyer.ts, plugins/acpPlugin/example/reactive/env.ts, plugins/acpPlugin/example/reactive/seller.ts, plugins/acpPlugin/src/index.ts
Improve Reactive Examples
- Improve docs
- Improve examples code
- Improve seller agent to check for pending active job before entering passive listening state to avoid missing out prior jobs
Requires repackaging of npm to include AcpJob in default package export. cc @jxx016 @Zuhwa 
Tested locally
=> [ACP Plugin][Docs] Improve Reactive Examples

plugins/acpPlugin/README.md, plugins/acpPlugin/example/agentic/buyer.ts, plugins/acpPlugin/example/reactive/buyer.ts, plugins/acpPlugin/src/acpPlugin.ts, plugins/acpPlugin/src/index.ts, plugins/acpPlugin/src/interface.ts
The main objective is to add a description as parameter for the onEvaluate function
=> feat: added new type and description to deliverable and enable export

plugins/acpPlugin/src/acpClient.ts, plugins/acpPlugin/src/acpPlugin.ts, plugins/acpPlugin/tools/deleteCompletedJobs.ts
Click the `Preview` tab and select a PR template:
- [Default Template](?expand=1&template=default.md)
- [Plugin](?expand=1&template=plugin.md)
=> adding tool to delete completed jobs

plugins/zytronPlugin/.gitignore, plugins/zytronPlugin/.npmignore, plugins/zytronPlugin/README.md, plugins/zytronPlugin/package.json, plugins/zytronPlugin/src/constants.ts, plugins/zytronPlugin/src/example.ts, plugins/zytronPlugin/src/index.ts, plugins/zytronPlugin/src/utils.ts, plugins/zytronPlugin/src/zytronPlugin.ts, plugins/zytronPlugin/src/zytronWallet.ts, plugins/zytronPlugin/tsconfig.json
This PR adds a Zytron Plugin integration, enabling on-chain interactions. The plugin allows users to query wallet information and send transactions.
- Plugin documentation: https://github.com/zypher-network/game-node/blob/main/plugins/zytronPlugin/README.md
- Other useful links: https://github.com/zypher-network
- README Validation
=> feat: add zytron plugin

plugins/acpPlugin/tools/reduceAgentState.ts
Click the `Preview` tab and select a PR template:
- [Default Template](?expand=1&template=default.md)
- [Plugin](?expand=1&template=plugin.md)
=> adding deleteCompletedJob and resetStates tools

plugins/acpPlugin/example/reactive/buyer-with-threading.ts, plugins/acpPlugin/example/reactive/seller-with-thread-example.ts, plugins/acpPlugin/example/reactive/seller-with-threading.ts
Click the `Preview` tab and select a PR template:
- [Default Template](?expand=1&template=default.md)
- [Plugin](?expand=1&template=plugin.md)
=> adding seller example with threading

plugins/acpPlugin/src/acpPlugin.ts
Click the `Preview` tab and select a PR template:
- [Default Template](?expand=1&template=default.md)
- [Plugin](?expand=1&template=plugin.md)
=> porting over agent state optimization from python acp plugin
